language: python
install:
 - git clone https://github.com/halindrome/linkchecker.git
 - sudo apt-get install libwww-perl libcss-dom-perl
script:
 - "! (perl -T linkchecker/bin/checklink -S 0  -q -b index.html |grep \"^\")"
env: WIDLPROC_PATH=$TRAVIS_BUILD_DIR/widlproc/obj/widlproc
